name: Test Build Docker Image

on: [push, pull_request]

jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
